using System.Collections;

namespace Samus
{
    class TwoCardRanking
    {
        //Class to evaluate starting hands, based on profit, ref. FTP
        internal static void PopulateHashTable(Hashtable ranking) //redo for limit holdem
        {
            ranking.Add("1", "AAo");
            ranking.Add("2", "KKo");
            ranking.Add("3", "QQo");
            ranking.Add("4", "JJo");
            ranking.Add("5", "AKs");
            ranking.Add("6", "AQs");
            ranking.Add("7", "TTo");
            ranking.Add("8", "AKo");
            ranking.Add("9", "AJs");
            ranking.Add("10","KQs");
            ranking.Add("11","99o");
            ranking.Add("12","ATs");
            ranking.Add("13","AQo");
            ranking.Add("14","KJs");
            ranking.Add("15","88o");
            ranking.Add("16","QJs");
            ranking.Add("17","KTs");
            ranking.Add("18","A9s");
            ranking.Add("19","AJo");
            ranking.Add("20","QTs");
            ranking.Add("21","KQo");
            ranking.Add("22","77o");
            ranking.Add("23","JTs");
            ranking.Add("24","A8s");
            ranking.Add("25","K9s");
            ranking.Add("26","ATo");
            ranking.Add("27","A5s");
            ranking.Add("28","A7s");
            ranking.Add("29","KJo");
            ranking.Add("30","66o");
            ranking.Add("31","T9s");
            ranking.Add("32","A4s");
            ranking.Add("33","Q9s");
            ranking.Add("34","J9s");
            ranking.Add("35","QJo");
            ranking.Add("36","A6s");
            ranking.Add("37","55o");
            ranking.Add("38","A3s");
            ranking.Add("39","K8s");
            ranking.Add("40","KTo");
            ranking.Add("41","98s");
            ranking.Add("42","T8s");
            ranking.Add("43","K7s");
            ranking.Add("44","A2s");
            ranking.Add("45","87s");
            ranking.Add("46","QTo");
            ranking.Add("47","Q8s");
            ranking.Add("48","44o");
            ranking.Add("49","A9o");
            ranking.Add("50","J8s");
            ranking.Add("51","76s");
            ranking.Add("52","JTo");
            ranking.Add("53","97s");
            ranking.Add("54","K6s");
            ranking.Add("55","K5s");
            ranking.Add("56","K4s");
            ranking.Add("57","T7s");
            ranking.Add("58","Q7s");
            ranking.Add("59","K9o");
            ranking.Add("60","65s");
            ranking.Add("61","T9o");
            ranking.Add("62","86s");
            ranking.Add("63","A8o");
            ranking.Add("64","J7s");
            ranking.Add("65","33o");
            ranking.Add("66","54s");
            ranking.Add("67","Q6s");
            ranking.Add("68","K3s");
            ranking.Add("69","Q9o");
            ranking.Add("70","75s");
            ranking.Add("71","22o");
            ranking.Add("72","J9o");
            ranking.Add("73","64s");
            ranking.Add("74","Q5s");
            ranking.Add("75","K2s");
            ranking.Add("76","96s");
            ranking.Add("77","Q3s");
            ranking.Add("78","J8o");
            ranking.Add("79","98o");
            ranking.Add("80","T8o");
            ranking.Add("81","97o");
            ranking.Add("82","A7o");
            ranking.Add("83","T7o");
            ranking.Add("84","Q4s");
            ranking.Add("85","Q8o");
            ranking.Add("86","J5s");
            ranking.Add("87","T6o");
            ranking.Add("88","75o");
            ranking.Add("89","J4s");
            ranking.Add("90","74s");
            ranking.Add("91", "K8o");
            ranking.Add("92", "86o");
            ranking.Add("93", "53s");
            ranking.Add("94", "K7o");
            ranking.Add("95", "63s");
            ranking.Add("96", "J6s");
            ranking.Add("97", "85o");
            ranking.Add("98", "T6s");
            ranking.Add("99", "76o");
            ranking.Add("100", "A6o");
            ranking.Add("101", "T2o");
            ranking.Add("102", "95s");
            ranking.Add("103", "84o");
            ranking.Add("104", "62o");
            ranking.Add("105", "T5s");
            ranking.Add("106", "95o");
            ranking.Add("107", "A5o");
            ranking.Add("108", "Q7o");
            ranking.Add("109", "T5o");
            ranking.Add("110", "87o");
            ranking.Add("111", "83o");
            ranking.Add("112", "65o");
            ranking.Add("113", "Q2s");
            ranking.Add("114", "94o");
            ranking.Add("115", "74o");
            ranking.Add("116", "54o");
            ranking.Add("117", "A4o");
            ranking.Add("118", "T4o");
            ranking.Add("119", "82o");
            ranking.Add("120", "64o");
            ranking.Add("121", "42o");
            ranking.Add("122", "J7o");
            ranking.Add("123", "93o");
            ranking.Add("124", "85s");
            ranking.Add("125", "73o");
            ranking.Add("126", "53o");
            ranking.Add("127", "T3o");
            ranking.Add("128", "63o");
            ranking.Add("129", "K6o");
            ranking.Add("130", "J6o");
            ranking.Add("131", "96o");
            ranking.Add("132", "92o");
            ranking.Add("133", "72o");
            ranking.Add("134", "52o");
            ranking.Add("135", "Q4o");
            ranking.Add("136", "K5o");
            ranking.Add("137", "J5o");
            ranking.Add("138", "43s");
            ranking.Add("139", "Q3o");
            ranking.Add("140", "43o");
            ranking.Add("141", "K4o");
            ranking.Add("142", "J4o");
            ranking.Add("143", "T4s");
            ranking.Add("144", "Q6o");
            ranking.Add("145", "Q2o");
            ranking.Add("146", "J3s");
            ranking.Add("147", "J3o");
            ranking.Add("148", "T3s");
            ranking.Add("149", "A3o");
            ranking.Add("150", "Q5o");
            ranking.Add("151", "J2o");
            ranking.Add("152", "84s");
            ranking.Add("153", "82s");
            ranking.Add("154", "42s");
            ranking.Add("155", "93s");
            ranking.Add("156", "73s");
            ranking.Add("157", "K3o");
            ranking.Add("158", "J2s");
            ranking.Add("159", "92s");
            ranking.Add("160", "52s");
            ranking.Add("161", "K2o");
            ranking.Add("162", "T2s");
            ranking.Add("163", "62s");
            ranking.Add("164", "32o");
            ranking.Add("165", "A2o");
            ranking.Add("166", "83s");
            ranking.Add("167", "94s");
            ranking.Add("168", "72s");
            ranking.Add("169", "32s");
        }
    }
}
